import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '@mdxeditor/editor/style.css'
import './globals.css'

import { ClerkProvider } from '@/services/clerk/components/ClerkProvider'
import { Toaster } from '@/components/ui/sonner'

const openSans = localFont({
  src: '/fonts/OpenSans-VariableFont_wdth,wght.ttf',
  preload: false
})

//👇 Configure the object for our second font
const roboto = localFont({
  src: '/fonts/Roboto-VariableFont_wdth,wght.ttf',
  preload: false
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body
          className={`${openSans.className} ${roboto.className} font-sans antialiased`}
        >
          {children}
          <Toaster
            toastOptions={{
              unstyled: true,
              classNames: {
                error: 'bg-red-400 p-2 rounded-md text-white',
                success: 'text-green-400',
                warning: 'text-yellow-400',
                info: 'bg-blue-400 p-2 rounded-md'
              }
            }}
          />
        </body>
      </html>
    </ClerkProvider>
  )
}
